name: Php Lint
on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  php-linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.3', '7.4', '8.0']
        ocp-version: ['^v21.0.0', '^v22.0.0', '^v23.0.0', 'dev-master']
    name: php${{ matrix.php-version }} lint
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up php${{ matrix.php-versons }}
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-version }}
        coverage: none
    - name: Install dependencies
      if: ${{ matrix.php-version != '8.0' }}
      run: composer i
    - name: Install dependencies
      if: ${{ matrix.php-version == '8.0' }}
      run: composer i --ignore-platform-reqs
    - name: Install OCP package
      if: ${{ matrix.php-version != '7.3' }}
      run: composer require --dev --with-all-dependencies christophwurst/nextcloud:${{ matrix.ocp-version }}
    - name: Lint
      run: composer run lint

  php-cs-fixer:
    name: php-cs check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up php${{ matrix.php-versions }}
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          tools: composer:v1
          coverage: none
      - name: Install dependencies
        run: composer i
      - name: Run coding standards check
        run: composer run cs:check
