# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

name: Static analysis

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - stable*

concurrency:
  group: psalm-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      ocp-branches: ${{ steps.versions.outputs.ocp-branches }}
    steps:
      - name: Checkout app
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Get version matrix
        id: versions
        uses: icewind1991/nextcloud-version-matrix@c2bf575a3516752db5ce2915499d3f694885e2c7 # master

  static-analysis:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        ocp-version: ${{fromJson(needs.matrix.outputs.ocp-branches)}}

    name: Nextcloud ${{ matrix.ocp-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up php
        uses: shivammathur/setup-php@c5fc0d8281aba02c7fda07d3a70cc5371548067d # v2
        with:
          php-version: 8.0
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: composer i

      - name: Install dependencies
        run: rm composer.lock && composer require --dev nextcloud/ocp:${{ matrix.ocp-version }} --ignore-platform-reqs --with-dependencies

      - name: Run coding standards check
        run: composer run psalm

  summary:
    runs-on: ubuntu-latest
    needs: static-analysis

    if: always()

    name: static-psalm-analysis-summary

    steps:
      - name: Summary status
        run: if ${{ needs.static-analysis.result != 'success' }}; then exit 1; fi
